name: backend_tests

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [develop]
  workflow_dispatch:
  push:
    branches:
    - develop
    - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      run: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0
        
    - name: Start Project
      run: |
        cd API
        nohup dotnet run &
        
    - name: Run Tests
      run: dotnet test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
