name: Custom_Cypress_Test

on:
  push:
  workflow_dispatch:

jobs:
  project_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the Docker command
        run: |
          docker run --name dev -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=secret -p 5432:5432 -d postgres:latest

      - name: Check out project
        uses: actions/checkout@v2
        
      - name: Setup dotnet project
        
        run: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0

      - name: Start Project
        run: |
          cd API
          nohup dotnet run &
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Run Cypress tests
        run: |
          ls
          cd client-app
          npx cypress run --record --key 88843a55-6fc2-41cf-b148-7d14bc7044b9