name: docker-push-master

on:
  workflow_run:
    types: [success]
    # Replace with the name of your "backend_tests" workflow
    workflows: backend_tests

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        #Github will hold the secrets
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 00tir2009/test-exam:latest
