name: docker-push-master

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  test_backend:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        run: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0
      - name: Run Tests
        run: dotnet test
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
      - name: Trigger secondary workflow
        uses: ./.github/workflows/docker-push-master.yml
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        #Github will hold the secrets
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 00tir2009/test-exam:latest
