name: test_and_release_master

on:
  pull_request:
    types: [closed]
    branches:
    - master
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  test_application:
      runs-on: ubuntu-latest
      steps:
      
      - name: Check if pull request is merged
        if: github.event.pull_request.merged == true
        continue-on-error: false
        run: echo "Pull request was merged."
        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET 6
        run: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0
          
      - name: Run Tests
        run: dotnet test
        # The .NET Core CLI will not send any telemetry data to Microsoft.
        # This is a recommended best practice for privacy.
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Run the Docker command
        run: |
          docker run --name dev -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -p 5432:5432 -d postgres:latest
      
      # nohup helps with running the dotnet build in the background

      - name: Start Project
        run: |
          cd API
          nohup dotnet run &
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
      
      - name: Run Cypress tests
        run: |
          ls
          cd client-app
          npm install
          npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
          
  docker:
    runs-on: ubuntu-latest
    needs: [test_application]
    steps:
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        #Github will hold the secrets
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 00tir2009/test-exam:latest
