name: test_and_release_master

on:
  pull_request:
    types: [closed]
    branches:
    - master
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  test_backend:
      runs-on: ubuntu-latest
      steps:
      
      - name: Check if pull request is merged
        if: github.event.pull_request.merged == true
        run: echo "Pull request was not merged. Stopping workflow."
        continue-on-error: false
        
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET 6
        run: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0
          
      - name: Run Tests
        run: dotnet test
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          
  docker:
    runs-on: ubuntu-latest
    needs: [test_backend]
    steps:
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        #Github will hold the secrets
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 00tir2009/test-exam:latest
